# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsh < Formula
  desc ""
  homepage ""
  version "1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/springload/aws-ssh/releases/download/v1.2/aws-ssh_1.2_darwin_amd64.tar.gz"
    sha256 "4baa88d4a5c03f4ab081eb7818a70c34e62478c71b4891acebe2144e763d9a74"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/springload/aws-ssh/releases/download/v1.2/aws-ssh_1.2_linux_amd64.tar.gz"
      sha256 "27b1e15d54c042bc31faaf107ad5a4d384a515c8e1f3adce3fde7d7207c8e4cc"
    end
  end

  def install
    bin.install "aws-ssh"
  end
end
