# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsh < Formula
  desc ""
  homepage ""
  version "2.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/springload/aws-ssh/releases/download/v2.2.5/aws-ssh_2.2.5_darwin_amd64.tar.gz"
      sha256 "3e6c9940d23f92c9fefa289478c76cf1ca7a3b7848c1c6dc42f7b4aaf2b263b9"

      def install
        bin.install "aws-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/springload/aws-ssh/releases/download/v2.2.5/aws-ssh_2.2.5_linux_amd64.tar.gz"
      sha256 "9027e2850b0caa51048dd83d0bb499cd66bd0462b24e1dc050ce6bc9ba6dec51"

      def install
        bin.install "aws-ssh"
      end
    end
  end
end
