# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Cssh < Formula
  desc ""
  homepage ""
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/springload/cssh/releases/download/v0.0.4/cssh_0.0.4_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fb7509906dc00c893cc6a5a6df2079c6fd2bd0426d7f08aa016a8ff391746d6a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/springload/cssh/releases/download/v0.0.4/cssh_0.0.4_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5a99a10ae007cbd1d21ba8a283f4c6be7e0b459de3736389802bc29d6f6f11d3"
    end
  end

  def install
    bin.install "cssh"
  end
end
