# This file was generated by GoReleaser. DO NOT EDIT.
class Cssh < Formula
  desc ""
  homepage ""
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://springload-software.s3-ap-southeast-2.amazonaws.com/cssh/0.2.2/cssh_0.2.2_darwin_amd64.tar.gz"
    sha256 "58c03151058f502125f5034122a556e368c83c63c6d6483e4b831287ab682f81"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://springload-software.s3-ap-southeast-2.amazonaws.com/cssh/0.2.2/cssh_0.2.2_linux_amd64.tar.gz"
      sha256 "65b82e954cf955ebf9dc2a4e7a024b139e98679d302035250edefd0bb2d2c7ed"
    end
  end

  def install
    bin.install "cssh"
  end
end
