# This file was generated by GoReleaser. DO NOT EDIT.
class EcsTool < Formula
  desc ""
  homepage ""
  version "1.5.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/springload/ecs-tool/releases/download/1.5.3/ecs-tool_1.5.3_darwin_amd64.tar.gz"
    sha256 "39d03324188b795fe6b6cc04c0820bfa134915a1a2d349cbe1851d7cabeb42bb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/springload/ecs-tool/releases/download/1.5.3/ecs-tool_1.5.3_linux_amd64.tar.gz"
      sha256 "d5c1f873d4f22060582e4448679111922c09aa7c7ac015de3ebb1148160443ca"
    end
  end

  def install
    bin.install "ecs-tool"
  end
end
