# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsTool < Formula
  desc ""
  homepage ""
  version "1.8.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/springload/ecs-tool/releases/download/1.8.0/ecs-tool_1.8.0_darwin_amd64.tar.gz"
      sha256 "32854818f9f92412675b8569fe44a724593ea99ebacc9082e6da00ee93a876d0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/springload/ecs-tool/releases/download/1.8.0/ecs-tool_1.8.0_linux_amd64.tar.gz"
      sha256 "40235eaa42e3afd7b779359b64a0dfd5848fc773ee7fdbe58591e89e906a08df"
    end
  end

  def install
    bin.install "ecs-tool"
  end
end
