# This file was generated by GoReleaser. DO NOT EDIT.
class LpAwsSaml < Formula
  desc "Temporary Credentials for AWS CLI for LastPass SAML login"
  homepage "https://github.com/springload/lp-aws-saml"
  version "0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/springload/lp-aws-saml/releases/download/v0.6/lp-aws-saml_0.6_darwin_amd64.tar.gz"
    sha256 "a9780cbd8d54134f4d5fe7d64a0370fdb9c9baf487225cc7c184a07a63900139"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/springload/lp-aws-saml/releases/download/v0.6/lp-aws-saml_0.6_linux_amd64.tar.gz"
      sha256 "4fefe980f2308a8bee81f2ed5901c968ff5a10091ecbffddfa21700bf4a11860"
    end
  end

  def install
    bin.install "lp-aws-saml"
  end
end
